# Generated by Django 3.2.8 on 2021-10-24 20:06

from django.db import migrations


def add_teacher(apps, schema_editor):
    Teacher = apps.get_model('polls', 'Teacher')
    t = Teacher(first_name='Strict',
                second_name='Teacher',
                task='Learn DB')
    t.save()


def add_homework(apps, schema_editor):
    Homework = apps.get_model('polls', 'Homework')
    hw = Homework(task_id=1,
                  deadline=7)
    hw.save()


def add_student(apps, schema_editor):
    Student = apps.get_model('polls', 'Student')
    s = Student(first_name='Diligent',
                second_name='Student',
                homework_id=1,
                solution='DB task is done')
    s.save()


def add_homework_results(apps, schema_editor):
    HomeworkResults = apps.get_model('polls', 'HomeworkResults')
    hw_results = HomeworkResults(author_id=1,
                                 homework_id=1,
                                 solution_id=1)
    hw_results.save()


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_teacher),
        migrations.RunPython(add_homework),
        migrations.RunPython(add_student),
        migrations.RunPython(add_homework_results),
    ]
